FROM python:3.11-slim as base

USER root

ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -qq && \
    apt-get install -y \
    curl \
    telnet \
    wget \
    default-jre \
    build-essential\
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
COPY requirements.txt /app/requirements.txt
RUN pip install -U --no-cache-dir -r /app/requirements.txt

RUN chgrp -R 0 /app && chmod -R g=u /app
COPY settings /app/settings
COPY src /app/src
COPY src/custom/chat_base_openai.py /usr/local/lib/python3.11/site-packages/langchain_openai/chat_models/base.py
COPY src/custom/chat_base_cohere.py /usr/local/lib/python3.11/site-packages/langchain_cohere/chat_models.py
COPY langgraph.json /app/langgraph.json
COPY log_config.json /app/log_config.json

RUN cp -r /app/src/.cache/data-gym-cache /tmp/data-gym-cache
ENV LANGCHAIN_TRACING_V2=false

ENV PYTHONPATH "${PYTHONPATH}:/app"

WORKDIR /app

USER 1001

CMD ["python", "src/api.py"]
